stages:
  - build

cache:
  paths:
    - node_modules/

build_job:
  image: node:18
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 week